require('plugins.lspconfig')
require('plugins.nvim-tree')
require('plugins.vimtex')
require('plugins.prettier')
require('plugins.lualine')
require('plugins.cmp')
require('plugins.conform')
require('plugins.settings')
